version: 2.1

executors:
  arachni_engine:
    description: Docker image with arachni.
    docker:
      - image: niemacka/arachni
commands:
  setup_arachni:
    description: downloads and extracts arachni tarball.
    steps:
      - run:
          command: |
            wget https://github.com/Arachni/arachni/releases/download/v1.5.1/arachni-1.5.1-0.5.12-linux-x86_64.tar.gz; \
            tar -xvzf arachni-1.5.1-0.5.12-linux-x86_64.tar.gz ; \
            rm arachni-1.5.1-0.5.12-linux-x86_64.tar.gz
  test:
    description: Passes or fails job based on given parameters.
    parameters:
      severity:
        description: Severity of vulnerabilities High, Medium, Low, Informational.
        type: string
    steps:
      - run:
          command: |
            RESULT=$(cat oss_template_report.txt | grep -e << parameters.severity >>)
            if [[ $RESULT == *"<< parameters.severity >>"* ]]; then \
                exit 1 \
            else \
                exit o \
            fi
jobs:
  scan:
    executor: arachni_engine
    description: Runs default arachni scan on target website.
    parameters: 
      site_name:
        description: url of site to be scanned.
        type: string
      severity:
        description: Severity of vulnerabilities High, Medium, Low, Informational.
        type: string
    steps:
      - setup_arachni
      - run:
          command: |
            cd arachni-1.5.1-0.5.12
            bin/arachni << parameters.site_name >>
            FILE=$(ls | grep -E "^ncar")
            bin/arachni_reporter "$FILE" --reporter=txt:outfile=oss_template_report.txt
      
      - store_artifacts:
           path: arachni-1.5.1-0.5.12/oss_template_report.txt
      - test
