version: 2.1

executors:
  arachni_engine:
    description: Docker image with arachni.
    docker:
      - image: niemacka/arachni
commands:
  setup_arachni:
    description: downloads and extracts arachni tarball.
    steps:
      - run:
          command: |
            wget https://github.com/Arachni/arachni/releases/download/v1.5.1/arachni-1.5.1-0.5.12-linux-x86_64.tar.gz; \
            tar -xvzf arachni-1.5.1-0.5.12-linux-x86_64.tar.gz ; \
            rm arachni-1.5.1-0.5.12-linux-x86_64.tar.gz
  test:
    description: Passes or fails job based on given parameters.
    parameters:
      severity:
        description: Severity of vulnerabilities High, Medium, Low, Informational.
        type: string
        default: "High"
    steps:
      - run:
          command: |
            set -e
            RESULT=$(cat /root/project/arachni-1.5.1-0.5.12/oss_template_report.txt | grep -E "Severity" | tr -d [:space:] | sed 's/\[~\]/,/g')
            IFS=',' read -r -a array \<\<\< "$RESULT"
            case << parameters.severity >> in High) for i in "${array[@]}"; do if [ "$i" == "High" ]; then exit 1; else exit 0; fi; done; ;; Medium) for i in "${array[@]}"; do if [ "$i" == "Medium" ] || [ "$i" == "High" ]; then exit 1; else exit 0; fi; done; ;; Low) for i in "${array[@]}"; do if [ "$i" == "Low" ] || [ "$i" == "Medium" ] || [ "$i" == "High" ]; then exit 1; else exit 0; fi; done; ;; Informational) for i in "${array[@]}"; do if [ "$i" == "Informational" ] || [ "$i" == "Low" ] || [ "$i" == "Medium" ] || [ "$i" == "High" ]; then exit 1; else exit 0; fi; done; ;; esac
jobs:
  scan:
    executor: arachni_engine
    description: Runs default arachni scan on target website.
    parameters: 
      site_name:
        description: url of site to be scanned.
        type: string
      severity:
        description: Severity of vulnerabilities High, Medium, Low, Informational.
        type: string
        default: "High"
    steps:
      - setup_arachni
      - run:
          command: |
            cd arachni-1.5.1-0.5.12
            bin/arachni << parameters.site_name >>
            FILE=$(ls | grep -E "^ncar")
            bin/arachni_reporter "$FILE" --reporter=txt:outfile=oss_template_report.txt
      - test:
          severity: << parameters.severity >>
      - store_artifacts:
          path: arachni-1.5.1-0.5.12/oss_template_report.txt
